name: Release

on:
  workflow_dispatch:

jobs:
  release:
    permission:
      contents: write
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
      run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{screts.GITHUB_TOKEN}}
